#! /bin/sh
#
# 	SQSL: demo applications shell wrapper
#
#	The Structured Query Scripting Language
#	(Borrowed from) The 4glWorks application framework
#	Copyright (C) 1992-2012 Marco Greco (marco@4glworks.com)
#
#	Initial release: Oct 92
#	Current release: Jan 12
#
#	This library is free software; you can redistribute it and/or
#	modify it under the terms of the GNU Lesser General Public
#	License as published by the Free Software Foundation; either
#	version 2.1 of the License, or (at your option) any later version.
#
#	This library is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#	Lesser General Public License for more details.
#
#	You should have received a copy of the GNU Lesser General Public
#	License along with this library; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

#
#  setup informix env vars / make your own adjustments
#
INFORMIXDIR=${INFORMIXDIR:-/usr/informix}
PATH=$PATH:$INFORMIXDIR/bin
#
SQSLDIR=${SQSLDIR:-`dirname $0`}
if [ $SQSLDIR = "." ]
then
    SQSLDIR=`pwd`
    if [ "$OSTYPE" = cygwin ]
    then
	SQSLDIR=`cygpath -w $SQSLDIR`
    fi
fi
DBPATH=${DBPATH:-$SQSLDIR}

modname=`basename $0`
export INFORMIXDIR PATH DBPATH SQSLDIR

if [ "$1" = "-t" ]
then
    shift
    if [ -n "$1" -a -f "$SQSLDIR/$modname.$1" ]
    then
	ext=$1
    fi
    shift
fi

if [ -z "$ext" ]
then
    for i in 4ge 4gi 4ae exe
    do
	if [ -f "$SQSLDIR/$modname.$i" ]
	then
	    ext=$i
	    break
	fi
    done
fi
case "$ext" in
  4gi)
    exec fgwgo $SQSLDIR/$modname.$ext $*
    ;;
  "")
    echo 'No application found'
    ;;
  *)
    exec $SQSLDIR/$modname.$ext $*
    ;;
esac
