#!/usr/bin/sh
#	"@(#) ldcyg 0.1"
#
#	ldcyg - shared library linking script on cygwin
#
#	The Structured Query Scripting Language
#	Copyright (C) 1992-2009 Marco Greco (marco@4glworks.com)
#
#	Initial release: Jan 09
#	Current release: Jan 09
#
#	This library is free software; you can redistribute it and/or
#	modify it under the terms of the GNU Lesser General Public
#	License as published by the Free Software Foundation; either
#	version 2.1 of the License, or (at your option) any later version.
#
#	This library is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#	Lesser General Public License for more details.
#
#	You should have received a copy of the GNU Lesser General Public
#	License along with this library; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

IDIR="`cygpath -u $INFORMIXDIR`"
INFORMIXDIR="`cygpath -w $INFORMIXDIR`"
CC=${CC:-cc}
export CC
OTHERARGS=

if test $# -lt 2
then
    echo "how about some parameters?"
    exit 1
fi

if test -z "$INFORMIXDIR" 
then 
    echo INFORMIXDIR not set
    exit 1
fi

for i in "$@"
do
    OTHERARGS="$OTHERARGS \"$i\""
done

# unless you exclude exports from the esql/c supplied libraries,
# the linker is likely to complain about some xxx_NO_THUNK_DATA symbol
# not existing, if linking in -mno-cygwin mode. passing -exclude-libs
# to the linker fixes this and does no harm to the standard cygwin gcc
#
eval $CC -shared $OTHERARGS  $IDIR/lib/isqlt09a.lib \
	-Wl,-exclude-libs,isqlt09a.lib
