#!/usr/bin/sh
#	"@(#) yacc 0.1"
#
#	yacc - a frontend for non pure parser generating yaccs
#
#	The Structured Query Scripting Language
#	Copyright (C) 1992-2012 Marco Greco (marco@4glworks.com)
#
#	Initial release: Feb 12
#	Current release: Feb 12
#
#	This library is free software; you can redistribute it and/or
#	modify it under the terms of the GNU Lesser General Public
#	License as published by the Free Software Foundation; either
#	version 2.1 of the License, or (at your option) any later version.
#
#	This library is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#	Lesser General Public License for more details.
#
#	You should have received a copy of the GNU Lesser General Public
#	License along with this library; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

if test -n "`grep PUREPARSER csqpc.h 2>&1`"
then
    if test -z "`grep PUREPARSER csqpc.h 2>&1 | fgrep '/*' 2>&1`"
    then
	sed -e 's/#define PUREPARSER/\/* #define PUREPARSER *\//g' \
	    csqpc.h > /tmp/csqpc.h$$
	cat /tmp/csqpc.h$$ > csqpc.h
    fi
fi
yacc $1; mv y.tab.c $2
